# Generated by Django 4.2.7 on 2024-06-28 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('for_whom', models.CharField(choices=[('men', 'men'), ('woman', 'woman'), ('kids', 'kids')], default='man', max_length=200)),
                ('gender', models.CharField(choices=[('men', 'men'), ('woman', 'woman')], default='man', max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Color_And_Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=150)),
                ('photos', models.ImageField(upload_to='shoes_images')),
                ('shoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes_api.shoes')),
            ],
        ),
    ]
