# Generated by Django 4.2.7 on 2024-06-28 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shoes_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoes',
            name='size',
            field=models.CharField(choices=[('UK6', 'UK6'), ('UK7', 'UK7'), ('UK8', 'UK8'), ('UK9', 'UK9'), ('UK10', 'UK10'), ('UK11', 'UK11'), ('UK12', 'UK12')], default='UK6', max_length=200),
        ),
    ]
