# Generated by Django 4.2.7 on 2024-06-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_api', '0002_shoes_user_alter_shoes_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
