# Generated by Django 4.2.7 on 2024-07-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_api', '0006_remove_vendor_address_alter_customer_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_photo',
            field=models.ImageField(default=1, upload_to='customer_profile_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='profile_photo',
            field=models.ImageField(default=1, upload_to='vendor_profile_image'),
            preserve_default=False,
        ),
    ]
