# Generated by Django 4.2.7 on 2024-07-03 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_api', '0008_remove_shoes_user_shoes_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to='shoes_api.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('men', 'men'), ('woman', 'woman'), ('kids', 'kids')], default='man', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='for_whom',
        ),
        migrations.AlterField(
            model_name='shoes',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='man', max_length=200),
        ),
        migrations.CreateModel(
            name='Order_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes_api.order')),
                ('shoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes_api.shoes')),
            ],
        ),
        migrations.AddField(
            model_name='shoes',
            name='product_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shoes_api.productcategory'),
            preserve_default=False,
        ),
    ]
