# Generated by Django 4.2.7 on 2024-07-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_api', '0009_order_productcategory_remove_shoes_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='product_category',
            field=models.CharField(choices=[('men', 'men'), ('woman', 'woman'), ('kids', 'kids')], default='man', max_length=200),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
