# Generated by Django 4.2.7 on 2024-07-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_api', '0010_alter_shoes_product_category_delete_productcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='category_name',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='SPORTS SHOES & SNEAKERS', max_length=200),
        ),
    ]
