# Generated by Django 4.2.7 on 2024-07-08 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_api', '0013_rename_category_name_shoes_shoes_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoes',
            name='shoes_category_name',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoes_category_name', models.CharField(choices=[('BOOTS', 'BOOTS'), ('CASUALS SHOES ', 'CASUALS SHOES '), ('FLIP FLOPS', 'FLIP FLOPS'), ('FORMAL SHOES', 'FORMAL SHOES'), ('SANDALS & FLOATERS', 'SANDALS & FLOATERS'), ('SPORTS SHOES & SNEAKERS', 'SPORTS SHOES & SNEAKERS')], default='SPORTS SHOES & SNEAKERS', max_length=200)),
                ('shoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes_api.shoes')),
            ],
        ),
    ]
