# Generated by Django 4.2.7 on 2024-09-04 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_api', '0015_shoes_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusByVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.BooleanField(default=False)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes_api.order_item')),
            ],
        ),
    ]
